# Generated by Django 3.2 on 2021-05-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0002_auto_20210506_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseDesigner',
        ),
    ]
