# Generated by Django 3.2 on 2021-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0003_delete_coursedesigner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
