# Generated by Django 3.2 on 2021-05-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0004_coursedesigner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cilo',
            fields=[
                ('cilo_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='coursedesigner',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=40, unique=True)),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('academic_start_year', models.IntegerField()),
                ('program', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('assessment', models.CharField(max_length=1000)),
                ('cilos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdb.cilo')),
                ('pre_request_course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userdb.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('evaluation_method', models.TextField()),
                ('percentage', models.TextField()),
                ('cilos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdb.cilo')),
            ],
        ),
    ]
