# Generated by Django 3.2 on 2021-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0005_auto_20210510_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedesigner',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
