# Generated by Django 3.2 on 2021-05-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0009_auto_20210510_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='cilos',
        ),
        migrations.AddField(
            model_name='assessment',
            name='cilos',
            field=models.ManyToManyField(to='userdb.Cilo'),
        ),
    ]
