# Generated by Django 3.2 on 2021-05-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0009_auto_20210510_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='cilo',
            name='child_cilos',
            field=models.ManyToManyField(related_name='child', to='userdb.Cilo'),
        ),
        migrations.AddField(
            model_name='cilo',
            name='parent_cilos',
            field=models.ManyToManyField(related_name='parent', to='userdb.Cilo'),
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='cilos',
        ),
        migrations.AddField(
            model_name='assessment',
            name='cilos',
            field=models.ManyToManyField(to='userdb.Cilo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='assessment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdb.assessment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_request_course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdb.course'),
        ),
    ]
