# Generated by Django 3.2 on 2021-05-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0011_alter_course_pre_request_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assessment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdb.assessment'),
        ),
    ]
