# Generated by Django 3.2 on 2021-05-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdb', '0012_alter_course_assessment'),
    ]

    operations = [
    ]
